deploy:
  image: quay.io/coreos/awscli
  only:
   - master
  script:
  - S3_RELATIVE_PATH="${CI_PROJECT_PATH//$REMOVE_PREFIX/}"
  - aws s3 sync ./ s3://$S3_BUCKET_NAME$S3_RELATIVE_PATH --delete --exclude ".git/*" --exclude ".DS_Store" --exclude ".gitlab-ci.yml"
